---
- name: Deploy logstash agent
  hosts: TEST
  gather_facts: False
  su: yes
  su_user: root
  
  tasks:
  - name: logstash configuration
    copy: src=templates/{{item}} dest=/opt/logstash/{{item}} owner=hdadm group=hdadm mode=0644
    with_items:
      - forward.conf
      - system-log.conf

  - name: logstash audit pattern
    copy: src=templates/grok-pattern/audit dest=/opt/logstash/patterns/audit owner=hdadm group=hdadm mode=0644
